[package]
name = "rusti"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.12"
warp = "0.3"
tokio = {version = "1", features = ["full"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"